sonar.projectKey=TheRenster_data5580_hw
sonar.organization=therenster


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=data5580_hw
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
sonar.sources=./data5580_hw

sonar.tests=./tests
sonar.python.coverage.reportPaths=coverage.xml

# Exclude all files in the test directory
sonar.exclusions=.github/**,**/coverage.xml,**/.coverage,**/htmlcov/**
