[tox]
envlist = py311
skipsdist = True

[testenv]
deps =
    pytest
    pytest-cov
commands = pytest --cov=data5580_hw --cov-report=xml --cov-config=tox.ini --cov-branch

[coverage:run]
relative_files = True
source = data5580_hw/
branch = True