import logging
from typing import Any

import requests

logger = logging.getLogger(__name__)


class LLMGateway:
    def __init__(self) -> None:
        self._api_key = ""
        self._model = "gemini-1.5-flash"
        self._timeout_seconds = 8
        self._enabled = False

    def init_app(self, app) -> None:
        self._api_key = (app.config.get("GEMINI_API_KEY") or "").strip()
        self._model = (app.config.get("GEMINI_MODEL") or "gemini-1.5-flash").strip()
        self._timeout_seconds = int(app.config.get("GEMINI_TIMEOUT_SECONDS") or 8)
        self._enabled = bool(self._api_key)
        if not self._enabled:
            logger.info("Gemini gateway disabled: GEMINI_API_KEY not set.")

    def summarize_prediction_differences(self, prompt: str) -> str:
        if not self._enabled:
            return (
                "LLM summary unavailable because Gemini is not configured. "
                "Set GEMINI_API_KEY to enable summaries."
            )

        url = (
            f"https://generativelanguage.googleapis.com/v1beta/models/{self._model}:generateContent"
            f"?key={self._api_key}"
        )
        body: dict[str, Any] = {
            "contents": [
                {
                    "parts": [{"text": prompt}],
                }
            ],
            "generationConfig": {
                "temperature": 0.2,
                "maxOutputTokens": 300,
            },
        }
        try:
            resp = requests.post(url, json=body, timeout=self._timeout_seconds)
            resp.raise_for_status()
            payload = resp.json()
            candidates = payload.get("candidates") or []
            if not candidates:
                return "No summary generated by Gemini."
            parts = (((candidates[0] or {}).get("content") or {}).get("parts") or [])
            text = "\n".join(
                str(p.get("text", "")).strip() for p in parts if isinstance(p, dict)
            ).strip()
            return text or "No summary generated by Gemini."
        except requests.Timeout:
            return "LLM summary timed out. Please retry in a moment."
        except Exception:
            logger.exception("Gemini API call failed")
            return "LLM summary unavailable due to an upstream API error."


llm_gateway = LLMGateway()
